#!/bin/sh

exec cmake \
     -DLLVM_BUILD_TYPE=Release \
     -DLLVM_ENABLE_PROJECTS="mlir" \
     -DLLVM_CCACHE_BUILD=ON \
     -DLLVM_ENABLE_ASSERTIONS=ON \
     -DLLVM_ENABLE_WARNINGS=OFF \
     -DLLVM_PARALLEL_LINK_JOBS=1 \
     -DCMAKE_PLATFORM_NO_VERSIONED_SONAME=ON \
     -DLLVM_TARGETS_TO_BUILD=X86 \
     -DLLVM_BUILD_TOOLS=ON \
     -DLLVM_BUILD_UTILS=ON \
     -DLLVM_ENABLE_ZLIB=OFF \
     -DLLVM_ENABLE_ZSTD=OFF \
     -DLLVM_BUILD_LLVM_DYLIB=ON \
     -DLLVM_LINK_LLVM_DYLIB=ON \
     -DMLIR_INCLUDE_INTEGRATION_TESTS=OFF \
     -DMLIR_INCLUDE_TESTS=OFF \
     -DMLIR_BUILD_MLIR_C_DYLIB=ON \
     -DMLIR_ENABLE_EXECUTION_ENGINE=ON \
     -DMLIR_ENABLE_SPIRV_CPU_RUNNER=ON \
     -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
     -DMLIR_LINK_MLIR_DYLIB=ON \
     "$@"

